### ISSUE TITLE
Taskmanager 0.3.1 crashes

### ISSUE THREAD

**Issue by TheMisterFish** [hideakitai/TaskManager#1]
After installing TaskManager version 0.3.1 and testing the examples, the arduino crashes and restarts. After downgrading to version 0.3.0 no crashes occur and everything runs smooth.

Tested on the Arduino Mega 2560

**Comment by hideakitai** [comment]
@lilfish Thank you for reporting. Which example has crashed? All?

And please let me know the version of AVR board (1.8.3?).

**Comment by hideakitai** [comment]
@lilfish Fixed in 0.3.2. Please let me know if you still have the problem. Thank you for reporting!
