### ISSUE TITLE
about delay() in libs

### ISSUE THREAD

**Issue by youxiaojie** [hideakitai/TaskManager#2]
dear sir,
I hope multitask in arduino, I read a lot of articles which mentioned "forget delay() in multi task".
but I see lots of libs using delay(), should I rewrite these libs?

**Comment by hideakitai** [comment]
Hi, could you let me know one example, please?

**Comment by youxiaojie** [comment]
eg I want to use 1602lcd which contain delay in libs, at the same time I hope to log into sd every 500ms... I see some articles says some lib are not friendly to multitask.

**Comment by hideakitai** [comment]
Ah, yes I recommend not to use such libraries which call `delay()` inside the function called in `loop()`. They also delay the other tasks. If you use a processor which has multiple cores, you can avoid it by using concurrent tasks. But this library does not aim it.

**Comment by youxiaojie** [comment]
thanks, by the way, I see taskmanagerIO in tcmenu project, does taskmanagerIO derived from this project? thanks!

**Comment by hideakitai** [comment]
I don't know but this library is interrupt free (aims no interrupt), but TaskManagerIO uses interrupt.
