### ISSUE TITLE
Tasks.erase(id) crashes arduino

### ISSUE THREAD

**Issue by TheMisterFish** [hideakitai/TaskManager#3]
```C++
for(int i = 0; i < Tasks.size(); i++) {
  Tasks.erase(i);
}
```

The above example crashes the Arduino Mega. 

I add the tasks like this:
```C++
Tasks.add([new_instruction, instruction_type, instruction_type_number]
          { tools_array[instruction_type][instruction_type_number]->run(); })
    ->startOnceAfter(1000);
```

The function also crashes when I try to create the task with a string name, and erasing using that string name.  

Using latest version on regular Arduino mega 2560 R3.

**Comment by hideakitai** [comment]
Hi, your first example crashes because the index is out of bounds.

```C++
for(int i = 0; i < Tasks.size(); i++) {
  Tasks.erase(i);
}
```

This example becomes like this if `Tasks.size()` is 3:

```C++
Tasks.erase(0); // Tasks.size() is 3 and max index is 2
Tasks.erase(1); // Tasks.size() is 2 and max index is 1
Tasks.erase(2); // Tasks.size() is 1 and max index is 0 => index is out of bounds
```

I couldn't understand what you are doing in the second example. Please give me a runnable (compilable and crashable) minimum example.

**Comment by hideakitai** [comment]
I've added `clear()` method to erase all tasks

**Comment by TheMisterFish** [comment]
> 
> 
> I've added `clear()` method to erase all tasks

Awesome! I'm going to test that a.s.a.p. - This solution probably closes my issue.

> 
> 
> Hi, your first example crashes because the index is out of bounds.
> 
> ```c++
> for(int i = 0; i < Tasks.size(); i++) {
>   Tasks.erase(i);
> }
> ```
> 
> This example becomes like this if `Tasks.size()` is 3:
> 
> ```c++
> Tasks.erase(0); // Tasks.size() is 3 and max index is 2
> Tasks.erase(1); // Tasks.size() is 2 and max index is 1
> Tasks.erase(2); // Tasks.size() is 1 and max index is 0 => index is out of bounds
> ```
> 
> I couldn't understand what you are doing in the second example. Please give me a runnable (compilable and crashable) minimum example.

So if I understand correctly, when I erase id 0. The task which used to be id 1, turns into id 0? if so, would this code work?:

```C++
for(int i = 0; i < Tasks.size(); i++) {
    Tasks.erase(0);
}
```

**Comment by hideakitai** [comment]
> So if I understand correctly, when I erase id 0. The task which used to be id 1, turns into id 0? if so, would this code work?:
> ```C++
> for(int i = 0; i < Tasks.size(); i++) {
>     Tasks.erase(0);
> }
> ```

Yes, I think it works. But I recommend accessing each task with names.

**Comment by hideakitai** [comment]
@lilfish If you still have any problems, please let me know. Closing.
