### ISSUE TITLE
Can TM bricked my Arduino Lenonardo

### ISSUE THREAD

**Issue by Schwenkner** [hideakitai/TaskManager#4]
I've added a simple snipped into Setup, my goal was to have variable subtasks.

```
	auto taskRef = Tasks.add<Speak>("Main");
	for (int i = 0; i < 10; i++)
	{
		char buffer[100];
		sprintf(buffer, "Subtask %d", i);
		taskRef->then<Speak>(buffer, 3, [&](TaskRef<Speak> task) {});
	}
	taskRef->startFps(1);

```
I used the "Speak" class from the docs, added debug messages for "enter", "begin" and "exit"

Running this on an Wemos D1 Mini worked fine, all 10 subtasks plus the main tasks are running.

Then I did it on a Leonardo. With 10 subtasks it stopped working, only showing 4 or 5 "begin" messages., no "enter" or "update" messages.
With up to 4 subtasks it did work, at 5 all subtasks did "update", but the debug messages printed have omitted characters.
I print out
```
Serial.print("Task ");
Serial.println(name);

```
but for subtast 3 and 4 the name was not shown.
I assumed, the "begin" for all the tasks took too long.

That's why I rearranged my code to first only declare the task and subtasks (7).
Unfortunatly I couldn't test this anymore, it seems the bootloader of the Leonardo is corrupt. The USB is no more recognized.
Pressing the reset button, the USB bootloader is shown for 2sec in the device manager, but vanishes. Others having same problem, meant a corrupted boot loader.

Is it possible that the test with the 5 tasks and the silly debug output could write into the boot loader?

**Comment by hideakitai** [comment]
Hi, could you give me your code that can reproduce the problem?

**Comment by Schwenkner** [comment]
Thanks for the fast response.

I'd added the code pasted here simply in the Setup and used the Speak class from the docs.
But I've added the full scetch here for you. On the Wemos D1 Mini (ESP8266) it works fine, only the Lenonardo had the problem, may be due to the lower memory available. This is also the reason I assume the boot loader was corrupted.

```
#include <TaskManager.h>

class Speak : public Task::Base {
    int num{ 0 };

public:
    Speak(const String& name)
        : Base(name) {
        Serial.begin(115200);
    }

    virtual ~Speak() {}

    // You can set paramters like builder pattern
    Speak* number(const int n) {
        num = n;
        return this;
    }

    virtual void update() override {
        Serial.print("Task ");
        Serial.println(name);
    }
};

// the setup function runs once when you press reset or power the board
void setup() {
	auto taskRef = Tasks.add<Speak>("Main");
	for (int i = 0; i < 10; i++)
	{
		char buffer[100];
		sprintf(buffer, "Subtask %d", i);
		taskRef->then<Speak>(buffer, 3, [&](TaskRef<Speak> task) {});
	}
	taskRef->startFps(1);
}

// the loop function runs over and over again until power down or reset
void loop() {
    Tasks.update();
}

```

**Comment by Schwenkner** [comment]
I think it has nothing to do with the number of the subtasks.

I've got my second Lenonardo. In the meanwhile I developed my sketch with the ESP Mini, wihout using any subtasks.
In that board it worked fine as expected.

Then I deploeyed that sketch to the Leonardo and it was again bricked. Same as before, bootloader does not work anymore.
Sketch didn't run at all, only deploeyed. Simple sketches without TaskManager I'd run on the Leonardo before, did work fine.

**Comment by hideakitai** [comment]
@Schwenkner Hi, sorry for the late reply.

I think this is simply the shortage of memory. I've added a feature to control the number of subtasks in v0.4.7 (only for AVR, it was 16 before v0.4.7 and limited to 4 in v0.4.7). Please define the number to 10 as follows and try it again.

```C++
#define TASKMANAGER_MAX_SUBTASKS 10  // define this before including TaskManager
#include <TaskManager.h>
```

If you still have the problem, your board doesn't have enough memory to handle many tasks. Please consider using a more powerful board.
